// This file will be auto-generated by jaspr_builder when @client components are added.
// Run: melos run landing:codegen
//
// jaspr 0.22+ generates lib/main.server.options.dart (containing defaultServerOptions)
// alongside the server entrypoint. Until you add a @client component, this file is empty.
